### ISSUE TITLE
Critical Error after clean install of 0.14.0.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#503] opened 2020-05-02 21:39 UTC
Yes, I know that something is wrong with this apk, but I’ve been too eager to install it and I’ve managed to do that before You warned me :) . 

After clean installation it acts like that:
https://trailofthelight.xyz/filerun/wl/?id=S5tkzytb1q4XR5ICr6Kf9narCBCNDHTD

_Android 9._

**Comment by SIRSteiner** [comment] 2020-05-02 22:45
I can confirm this issue.
Additionally we should recomment a clean installation because of changed the notification channel(s). After an update the old notification channel "Handy News Reader" stays in system settings and only after a clean installation it disappers.

**Comment by yanus171** [comment] 2020-05-03 04:37
Did you send me that critical write?

**Comment by SIRSteiner** [comment] 2020-05-03 09:29
One minute ago ;-)

**Comment by SIRSteiner** [comment] 2020-05-08 18:58
In DatabaseHelper.java line 85 to 89 you try to import the backup while the is no permission to the storage. Therefore we get an error at the first start. Is it enough to remove these lines?

**Comment by yanus171** [comment] 2020-05-08 19:24
I have pushed the fix. Try please

**Comment by SIRSteiner** [comment] 2020-05-08 19:34
Yes, it works. Thank you!

**Closed** 2023-06-12 09:14 UTC
Labels: bug
