### ISSUE TITLE
GUI Complete crash with new version 0.8.2 ; 0.8.0 fine.

### ISSUE THREAD

**Issue by businessBoris** [yanus171/Handy-News-Reader#201] opened 2019-05-15 10:11 UTC
As title. I'm not able to downgrade to 0.8.0 which worked for me. App installed via f-droid.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at android.graphics.Color.parseColor(Color.java:1384)
	at ru.yanus171.feedexfork.fragment.EntryFragment.UpdateFooter(EntryFragment.java:866)
	at ru.yanus171.feedexfork.fragment.EntryFragment$EntryPagerAdapter.displayEntry(EntryFragment.java:1253)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:1075)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:110)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

-------------------
Version : 0.8.2
Version Code: 155
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: ONEPLUS A6013
Android Version : 9
User : OnePlus
Total Internal memory : 242142883840
Available Internal memory : 189450551296
-------------------

**Comment by businessBoris** [comment] 2019-05-15 10:13
Text size above not mine. Straight copy from exception email.

**Comment by yanus171** [comment] 2019-05-15 11:30
Try it https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.3

**Comment by businessBoris** [comment] 2019-05-15 19:47
Thank you. Not installing properly for the moment but that's my fault - permissions on phone.
Come back to you ASAP.

**Comment by businessBoris** [comment] 2019-05-16 14:21
I can't seem to get this installed. No idea what's wrong. Have change install permissions and disabled AV.
Phone spec in original message.

**Comment by yanus171** [comment] 2019-05-16 16:03
You should uninstall existing app version first

**Comment by businessBoris** [comment] 2019-05-16 21:29
I tried that eventually; I lost a significant proportion of my feeds. I couldn't see a way to import them back again from an old backup so I think I'm going to look for another app.
Thank you again for replying.

**Comment by yanus171** [comment] 2019-05-17 02:51
There is an Import from opml menu item in Feed edit screen. You can import 
autobackup.opml
С уважением, Алексей

Alex Plumbley-Jones <notifications@github.com> 17 мая 2019 г. 0:29:17 написал:

**Comment by lgasp** [comment] 2019-05-17 06:57
I have the same issue with version 0.82.

I installed version 0.83 from above link and it works without the issue.

**Comment by crti** [comment] 2019-05-17 11:19
Same error report as businessBoris except: 
`Android Version : 7.1.2
User : aosadmin
Total Internal memory : 26401026048
Available Internal memory : 8185995264`
So this is LineageOS 14.1. Could also not install ru.yanus171.feedexfork_0.8.3_156.apk because of error message "Package is in conflict with existing package with the same name." 
Avoided uninstalling for now to not loose Feed settings and wait for 0.8.3. Update availability in F-Droid hopefully fixing this. Thanks

**Comment by yanus171** [comment] 2019-05-17 14:13
Feed data and app settings should be auto restored if autobackup is enabled 
in app settings. You can also create manual backup before uninstall (export 
to opml in feeds settings screen)

**Comment by lgasp** [comment] 2019-05-17 14:15
I can confirm that uninstalling 0.82 and installing 0.83 my feeds and settings were still there

**Comment by crti** [comment] 2019-05-18 07:03
OK, did work also for me. I hope I can update 0.83 trough F-Droid.

**Comment by SIRSteiner** [comment] 2019-06-03 22:59
In F-Droid app there is v0.8.6. So we can close this issue.

**Closed by SIRSteiner** 2019-06-03 22:59 UTC
Labels: bug
